#logging:
#    level:
#        org:
#            # Logging SQL Statements with JdbcTemplate
#            springframework:
#                jdbc:
#                    core:
#                        JdbcTemplate: DEBUG
#                        StatementCreatorUtils: TRACE

spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: password
        url: jdbc:h2:mem:testDb; # for Test resource
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        sql:
            init:
                mode: always
                schema-locations: classpath:h2/schema.sql, classpath:h2/ddl.sql

    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
                trace: true

spring.batch:
    # this property will not create table when you use @EnableBatchProcessing
    jdbc.initialize-schema: always
    # this property will no when you use @EnableBatchProcessing
    # this property is to disable the Auto run the Job
    job.enabled: false