#logging:
#    level:
#        org:
#            # Logging SQL Statements with JdbcTemplate
#            springframework:
#                jdbc:
#                    core:
#                        JdbcTemplate: DEBUG
#                        StatementCreatorUtils: TRACE

spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password: password
        url: jdbc:h2:mem:testDb; # for Test resource
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                jdbc:
                    fetch_size: 10000
                    batch_size: 10000
                enable_lazy_load_no_trans: true
                format_sql: true # To beautify or pretty print the SQL
                show-sql: true # To print Sql query in Log
                hbm2ddl:
                    auto: create-drop

    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
                trace: true

spring.batch:
    jdbc.initialize-schema: always
    job.enabled: false